#!/usr/bin/env bash
set -euo pipefail

DOTFILES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
BACKUP_SUFFIX="$(date +%Y%m%d%H%M%S)"

configs=(
  ghostty
  kitty
  nvim
  tmux
  wezterm
  yazi
  zed
)

absolute_existing_path() {
  local path="$1"
  local dir
  local base

  if [[ -d "$path" ]]; then
    (cd "$path" && pwd -P)
  elif [[ -e "$path" ]]; then
    dir="$(cd "$(dirname "$path")" && pwd -P)"
    base="$(basename "$path")"
    printf '%s/%s\n' "$dir" "$base"
  else
    return 1
  fi
}

resolve_symlink_target() {
  local link="$1"
  local target="$2"

  if [[ "$target" != /* ]]; then
    target="$(dirname "$link")/$target"
  fi

  absolute_existing_path "$target"
}

link_config() {
  local name="$1"
  local source="$DOTFILES_DIR/$name"
  local target="$CONFIG_HOME/$name"
  local source_abs

  if [[ ! -e "$source" ]]; then
    printf 'skip: %s does not exist in dotfiles\n' "$name"
    return
  fi

  if [[ -d "$source" ]] && ! find "$source" -type f ! -name .gitkeep -print -quit | grep -q .; then
    printf 'skip: %s only contains placeholders\n' "$name"
    return
  fi

  source_abs="$(absolute_existing_path "$source")"

  if [[ -L "$target" ]]; then
    local current
    local current_abs
    current="$(readlink "$target")"
    if current_abs="$(resolve_symlink_target "$target" "$current")" && [[ "$current_abs" == "$source_abs" ]]; then
      printf 'ok:   %s already linked\n' "$name"
      return
    fi
    printf 'move: %s existing symlink -> %s.bak-%s\n' "$target" "$target" "$BACKUP_SUFFIX"
    mv "$target" "$target.bak-$BACKUP_SUFFIX"
  elif [[ -e "$target" ]]; then
    printf 'move: %s -> %s.bak-%s\n' "$target" "$target" "$BACKUP_SUFFIX"
    mv "$target" "$target.bak-$BACKUP_SUFFIX"
  fi

  printf 'link: %s -> %s\n' "$target" "$source"
  ln -s "$source" "$target"
}

ghostty_platform() {
  case "$(uname -s)" in
    Darwin)
      printf 'macos'
      ;;
    Linux)
      printf 'linux'
      ;;
    *)
      printf ''
      ;;
  esac
}

configure_ghostty_platform() {
  local name="ghostty"
  local source="$DOTFILES_DIR/$name"
  local selector="$source/platform.local"
  local marker="# Generated by dotfiles/bootstrap.sh"
  local platform
  platform="$(ghostty_platform)"

  if [[ -z "$platform" || ! -f "$source/platform/$platform" ]]; then
    printf 'skip: %s has no platform overlay for %s\n' "$name" "$(uname -s)"
    return
  fi

  if [[ -e "$selector" ]]; then
    if ! head -n 1 "$selector" | grep -qxF "$marker"; then
      printf 'move: %s -> %s.bak-%s\n' "$selector" "$selector" "$BACKUP_SUFFIX"
      mv "$selector" "$selector.bak-$BACKUP_SUFFIX"
    fi
  fi

  printf 'write: %s\n' "$selector"
  {
    printf '%s\n' "$marker"
    printf '# This file is machine-local and intentionally ignored by git.\n'
    printf 'config-file = platform/%s\n' "$platform"
  } >"$selector"
}

is_known_config() {
  local name="$1"

  for config in "${configs[@]}"; do
    if [[ "$config" == "$name" ]]; then
      return 0
    fi
  done

  return 1
}

should_process_config() {
  local name="$1"

  for config in "${selected_configs[@]}"; do
    if [[ "$config" == "$name" ]]; then
      return 0
    fi
  done

  return 1
}

mkdir -p "$CONFIG_HOME"

if [[ "$#" -gt 0 ]]; then
  selected_configs=("$@")

  for config in "${selected_configs[@]}"; do
    if ! is_known_config "$config"; then
      printf 'error: unknown config %s\n' "$config" >&2
      exit 1
    fi
  done
else
  selected_configs=("${configs[@]}")
fi

for config in "${configs[@]}"; do
  if ! should_process_config "$config"; then
    continue
  fi

  link_config "$config"

  if [[ "$config" == "ghostty" ]]; then
    configure_ghostty_platform
  fi
done
